local map = require("core.keymap.map")
local explore = nvim.keymap.explore
local win  = nvim.keymap.win

-- Keymappings
map.nmap(explore.open_explore, ":NetrwOpenFileTree<CR>")
local netrw_mapping = function()
    map.bnmap(win.resize_vwin_bigger,        ":vertical resize +1<CR>")
    map.bnmap(win.resize_vwin_smaller,       ":vertical resize -1<CR>")
    map.bnmap(win.resize_hwin_bigger,        ":horizontal resize +1<CR>")
    map.bnmap(win.resize_hwin_smaller,       ":horizontal resize -1<CR>")
    map.bnmap(win.focus_left_win,            ":wincmd h<CR>")
    map.bnmap(win.focus_right_win,           ":wincmd l<CR>")
    map.bnmap(win.focus_up_win,              ":wincmd k<CR>")
    map.bnmap(win.focus_down_win,            ":wincmd j<CR>")
    map.bnmap(explore.close_explore,         ":NetrwCloseFileTree<CR>")
    map.bnmap(explore.move_to_prev_item,     "<Up>")
    map.bnmap(explore.move_to_next_item,     "<Down>")
    map.bnmap(explore.move_to_parent_folder, ":NetrwExitDirectory<CR>")
    map.bnmap(explore.mark_or_unmark,        "mf")
    map.bnmap(explore.move_to_current_folder,":NetrwOpenFileOrDirectory<CR>")
    map.bnmap(explore.edit,                  ":NetrwEditFileOrDirectory<CR>")
    map.bnmap(explore.cut,                   ":NetrwCutFile<CR>")
    map.bnmap(explore.copy,                  ":NetrwCopyFile<CR>")
    map.bnmap(explore.paste,                 ":NetrwPasteFile<CR>")
    map.bnmap(explore.delete,                ":NetrwRemoveRecursive<CR>")
    map.bnmap(explore.rename,                ":NetrwRename<CR>")
    map.bnmap(explore.create_file,           ":NetrwCreateFile<CR>")
    map.bnmap(explore.create_directory,      ":NetrwCreateDirectory<CR>")
end
vim.api.nvim_create_autocmd("FileType", { pattern = "netrw", callback = netrw_mapping })
